server:
  port: 8000

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.77.130:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: gulimall-member

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    host: 192.168.77.130
    port: 6379

  session:
    store-type: redis

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  global-config:
    db-config:
      id-type: auto



