server:
  port: 20000

spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    host: 192.168.77.130
    port: 6379


  thymeleaf:
    cache: false



