server:
  port: 9000

spring:
  application:
    name: gulimall-order
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.77.130:3306/gulimall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  rabbitmq:
    host: 192.168.77.130
    port: 5672
    virtual-host: /
    username: guest
    password: guest



mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml

  #\u8BBE\u7F6E\u5B9E\u4F53\u7C7B\u7684\u81EA\u589E\u4E3B\u952E
  global-config:
    db-config:
      id-type: auto
