server:
  port: 12000

spring:
  application:
    name: gulimall-search
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
<<<<<<< HEAD
=======
  thymeleaf:
    cache: false
>>>>>>> 72bc0255c064281d23566ef8d7c84b1a747d7842


logging:
  level:
    com.xunqi.gulimall.search: debug
    root: warn
  pattern:
    console: "%d{yyyy-MM-dd} [%thread] - %msg%n"
<<<<<<< HEAD
=======

>>>>>>> 72bc0255c064281d23566ef8d7c84b1a747d7842
