server:
  port: 40000


spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    sentinel:
      transport:
        #配置sentinel dashboard地址
        dashboard: localhost:8080

  redis:
    host: 192.168.77.130
    port: 6379
  session:
    store-type: redis

#配置线程池
gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'


