server:
  port: 40000


spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.77.130
    port: 6379
  session:
    store-type: redis




